### ISSUE TITLE
Basic problems

### ISSUE THREAD

**Issue by fs-tom** [fsdonks/demand_builder#1]
We have no testdata for this.  Thus, no sample files.  The "documentation" is really a user-guide, and going from cursory evaluation of comments [without seeing examples of the input data being transformed], how are we to infer if this is correct or if it works? 

Also, lots of duplication of effort rather than using existing libraries, particulary with tabular data and tad delimited file processing / parsing.  Lacking checks on inputs to test for conformity (burden is on the user....looks like many opaque failure possibilities).  I think maintaining this will be difficult as is.

Finally, the "unit node detail" option should be default for reading from FORGE (it's commented out).  Otherwise, it's a somewhat-jankier duplication of effort from [here](https://github.com/fsdonks/m4/blob/master/src/marathon/processing/forgereader.clj) with usage [here](https://github.com/fsdonks/m4/blob/master/src/marathon/processing/surgereader.clj) .

**Comment by mpavlak1** [comment]
refactored demand builder in formatter and forgeformatter ns
