### ISSUE TITLE
Duplicate CONSOLIDATED

### ISSUE THREAD

**Issue by fs-craig** [fsdonks/demand_builder#10]
Warn the user if one of the CONSOLIDATED demands has two or more records for one SRC and one force list code.  This would have highlighted a mistake in the input data that we were given. 

In addition to warning the user, go ahead and combine the quantities to create a single demand record.

**Comment by fs-craig** [comment]
Give the user the list of duplicate records as well.

**Comment by mpavlak1** [comment]
Checks for duplicate records in cons file (same SRC and ForceCode)
Prints duplicates to user in repl
Creates file containing duplicates
Sums the quantity of duplicates and merges to be a single record
