### ISSUE TITLE
Out of Scope Force List Codes

### ISSUE THREAD

**Issue by fs-craig** [fsdonks/demand_builder#11]
create an output table txt file which lists the force list codes in the MAP which aren't in the CONSOLIDATED and vice versa, so this table has two fields:  "Code" and "Reason".  Reason is "Not in Consolidated" or "Not in MAP".

**Comment by mpavlak1** [comment]
checks for fcs in map but not in cons and in cons but not in map
creates file containing missing vignettes and from which file they are not found
