### ISSUE TITLE
Demand Group shifter

### ISSUE THREAD

**Issue by fs-craig** [fsdonks/demand_builder#14]
Demand Group end day shifter will add to the duration of all demands for that demand group.  This will cause phases to overlap.  Shifting the start and end days should behave just like changing the start and duration of the MAP file.  If the end day is to be shifted, the last demand record for an SRC for that demand group should only be shifted if it is active on the global last day for that demand group.

**Comment by mpavlak1** [comment]
Now should only be shifting when record starts on the global last day.

The 'use existing demand button' allows users to specify pre-existing demand-records without have to re-rerun demand-builder.
