### ISSUE TITLE
Remove 0 Quantity Vignetes

### ISSUE THREAD

**Issue by ghost** [fsdonks/demand_builder#3]
Don't need to add vignettes with a quantity of 0 to the DemandRecords.

**Comment by fs-craig** [comment]
tested in "duplicates" test.

**Comment by mpavlak1** [comment]
added filter to check for 0 quantity records

**Comment by fs-craig** [comment]
calling demand_builder in test/resources/duplicates/Input results in the 0 quantity consolidated demand being reflected in the output.

**Comment by fs-craig** [comment]
In the same output, the consolidated quantities for 01285K000 should be reflected and they currently are not.  The quantity on that SRC should be 5.  see duplicates/Output/Input_DEMAND_expected.txt

**Comment by fs-craig** [comment]
This was already fixed in the formatter ns.
