### ISSUE TITLE
Why IllegalArgumentException 

### ISSUE THREAD

**Issue by fs-craig** [fsdonks/demand_builder#5]
Even though the chart is being rendered, I get this exception.  Just annoying.

demand_builder.core> (root->demand-file zer)
Created demand file C:\Users\craig.j.flewelling\workspace\demand_builder_tests\inactive_extension\Input\Input_DEMAND.txt
IllegalArgumentException No implementation of method: :set-colors of protocol: #'proc.stacked/IColorable found for class: nil  clojure.core/-cache-protocol-fn (core_deftype.clj:583)

**Comment by mpavlak1** [comment]
Fixed, was passing nil to set-colors when no color-map given by user. 
Will only try to set-colors when valid argument exist, should stop throwing exception
