### ISSUE TITLE
Map ends Forge early

### ISSUE THREAD

**Issue by fs-craig** [fsdonks/demand_builder#7]
Since we can handle extensions to the Forge files, we need to be able to handle shortening as well.  If the map shortens a Forge demand, it should work as expected.  I'm adding an early_map test to the test resources.  As you can see, the output looks janky.  I'll make expected output when I have a chance.

**Comment by fs-craig** [comment]
Expected output is made.  Pushing shortly.

**Comment by mpavlak1** [comment]
Will now generate a file to show which records were adjusted.
If syncing to match the map ending causes 0 or negative durations, they will be removed.
