### ISSUE TITLE
Duplicate SRC in Forge

### ISSUE THREAD

**Issue by fs-craig** [fsdonks/demand_builder#8]
If the SRC appears on more than one line in the forge file, merge the demands into one demand record.  This prevent duplicate demand records, which won't be handled by m4.

**Comment by fs-craig** [comment]
Might as well add these SRCs and event code to the duplicate CONSOLIDATED list.

**Comment by mpavlak1** [comment]
Added check for duplicate records (same SRC and StartDay)
Will print the duplicates to the user in repl
Creates a file containing list of duplicate records
Sums the quantity of duplicate records as merges to be only a single records
